CREATE OR REPLACE STORAGE INTEGRATION IMPORT_FINNHUB_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::169961544497:role/SnowflakeRole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://import-finnhub/');


DESC INTEGRATION IMPORT_FINNHUB_INT;



CREATE OR REPLACE DATABASE BATCH_DB;
CREATE SCHEMA IF NOT EXISTS LANDING_FINNHUB;
CREATE SCHEMA IF NOT EXISTS HISTORY_FINNHUB;
CREATE SCHEMA IF NOT EXISTS REPLICA_FINNHUB;


CREATE OR REPLACE STAGE BATCH_DB.LANDING_FINNHUB.NEWS
    URL = 's3://import-finnhub/'
    STORAGE_INTEGRATION = IMPORT_FINNHUB_INT
    DIRECTORY = (ENABLE = TRUE AUTO_REFRESH = TRUE);


CREATE OR REPLACE TABLE BATCH_DB.LANDING_FINNHUB.FINNHUB_NEWS (
	CATEGORY VARCHAR,
	DATETIME NUMBER,
	HEADLINE VARCHAR,
	ID NUMBER,
	IMAGE VARCHAR,
	RELATED VARCHAR,
	SOURCE VARCHAR,
	SUMMARY VARCHAR,
	URL VARCHAR
);


CREATE OR REPLACE FILE FORMAT BATCH_DB.LANDING_FINNHUB.NEWS
TYPE = JSON
STRIP_OUTER_ARRAY = TRUE;


CREATE OR REPLACE PIPE BATCH_DB.LANDING_FINNHUB.NEWS
AUTO_INGEST = TRUE
AS
COPY INTO BATCH_DB.LANDING_FINNHUB.FINNHUB_NEWS
FROM (
  SELECT 
    $1:category::VARCHAR AS CATEGORY,
    $1:datetime::NUMBER AS DATETIME,
    $1:headline::VARCHAR AS HEADLINE,
    $1:id::NUMBER AS ID,
    $1:image::VARCHAR AS IMAGE,
    $1:related::VARCHAR AS RELATED,
    $1:source::VARCHAR AS SOURCE,
    $1:summary::VARCHAR AS SUMMARY,
    $1:url::VARCHAR AS URL
  FROM @BATCH_DB.LANDING_FINNHUB.NEWS
)
FILE_FORMAT = (FORMAT_NAME = 'BATCH_DB.LANDING_FINNHUB.NEWS');


SHOW PIPES;


select SYSTEM$PIPE_STATUS( 'NEWS' );
